/**
 * Every user-facing string, mirroring `app/src/main/res/values/strings.xml`.
 *
 * Generated once from the Android resources so the harness shows exactly the words the phone
 * shows. From here on this file is the design source: change the copy here, see it in the
 * browser, then carry the change back to strings.xml when the Android side catches up.
 *
 * Format specifiers are left in Android's form (`%1$s`, `%2$d`) and filled by `format` below,
 * so a string can be moved between the two without editing it.
 */
export const S = {
  app_name: 'Keyguard',
  ime_label: 'Keyguard Keyboard',
  subtype_label_en_us: 'English (US)',
  key_backspace: '⌫',
  key_enter: '↵',
  key_shift: '⇧',
  key_shift_active: '⬆',
  key_shift_locked: '⇪',
  key_next_keyboard: '🌐',
  key_space_description: 'Space',
  toolbar_emoji: '🙂',
  toolbar_emoji_description: 'Emoji',
  toolbar_paste: '📋',
  toolbar_paste_description: 'Paste',
  toolbar_select_all: '⬚',
  toolbar_select_all_description: 'Select all',
  toolbar_cursor_left: '◀',
  toolbar_cursor_left_description: 'Move cursor left',
  toolbar_cursor_right: '▶',
  toolbar_cursor_right_description: 'Move cursor right',
  emoji_close: 'ABC',
  emoji_close_description: 'Back to keyboard',
  key_backspace_description: 'Backspace',
  action_rewrite: 'Remove it',
  action_dismiss: 'Ignore',
  action_get_help: 'Get help now',
  action_send_anyway: 'Send anyway',
  action_go_back: 'Let me fix it',
  warning_detail: 'Flagged as: %1$s',
  warning_blocked: 'Typing paused. Delete the highlighted text, or tap Ignore to carry on.',
  confirm_send_title: 'Are you sure you want to send this?',
  crisis_summary: 'It sounds like you\'re going through something really hard.',
  crisis_detail: 'You don\'t have to deal with this alone. You can talk to someone right now, any time, for free — %1$s.',
  category_pii: 'Personal information',
  category_harassment: 'This could hurt someone',
  category_solicitation: 'Safety concern',
  category_self_harm: 'Support',
  category_violence: 'Reads as a threat',
  category_meetup: 'Meeting in person',
  category_substance: 'Substances',
  setup_progress_privacy: 'Step 1 of 3 · Read how your typing is protected',
  setup_progress_enable: 'Step 2 of 3 · Turn on the Keyguard keyboard',
  setup_progress_choose: 'Step 3 of 3 · Choose Keyguard while typing',
  setup_progress_ready: 'All set · Keyguard is ready to use',
  setup_disclosure_heading: 'What this keyboard can see',
  setup_disclosure_body: 'To warn you as you type, Keyguard reads the text you type on its own keyboard.\n\nWhat happens to it:\n\n• Checking happens on this device, using a built-in list of patterns. No network is involved.\n• Nothing you type is saved. Text is held in memory only while you\'re typing and is discarded when you switch fields.\n• Password fields are never checked. Detection and network activity are switched off completely for them.\n• Nothing you type is ever written to logs or crash reports.\n\nKeyguard can only see what you type on its own keyboard. It cannot read messages you receive, and it cannot see what you type on any other keyboard.',
  setup_disclosure_network: 'Double-checking (optional, off by default) is the one exception. If you turn it on, a flagged phrase and up to a few recent messages are sent to a server to be reviewed by an AI — this is what tells “I want to die of embarrassment” apart from something serious. Even then, your full typing is never sent, and nothing is sent from password fields. You can turn it off at any time.',
  setup_disclosure_accept: 'I\'ve read what this keyboard can see',
  onboarding_enable_heading: 'Turn on the keyboard',
  onboarding_enable_body: 'Android keeps keyboards switched off until you allow them. This opens the system list — turn on Keyguard there, then come back.',
  onboarding_choose_heading: 'Switch to Keyguard',
  onboarding_choose_body: 'Keyguard is allowed, but something else is still your active keyboard. Choose Keyguard from the list to start using it.',
  onboarding_ready_heading: 'Try it',
  onboarding_ready_body: 'Keyguard is ready. Type in the box below — try “my address is 123 Main Street” to see what a warning looks like.',
  onboarding_continue: 'Continue',
  onboarding_done: 'Done',
  onboarding_skip: 'Skip for now',
  onboarding_settings: 'All settings',
  setup_enable_button: 'Open keyboard settings',
  setup_switch_button: 'Choose keyboard',
  setup_status_enabled: 'Keyguard is turned on.',
  setup_status_disabled: 'Keyguard is not turned on yet.',
  setup_intensity_heading: 'How forceful should warnings be?',
  setup_intensity_subtle: 'Subtle — show a small warning, never block sending',
  setup_intensity_standard: 'Standard — expand serious warnings and confirm before sending',
  setup_intensity_insistent: 'Insistent — expand and confirm for anything concerning',
  setup_try_placeholder: 'Type something like “my address is 123 Main Street”',
  stats_heading: 'Is it working?',
  stats_hint: 'Counts only — never the text you typed. “Changed” means a warning appeared and the message was deleted instead of sent.',
  stats_none: 'No warnings shown yet.',
  stats_body: 'Warnings shown   %1$d\nChanged          %2$d\nSent anyway      %3$d\nChange rate      %4$s',
  stats_engine: 'Rule pack v%1$d (%2$s) · %3$d terms · on-device only, no network',
  stats_reset: 'Reset counts',
  appearance_keyboard_heading: 'Keyboard size',
  appearance_keyboard_hint: 'Changes apply the next time the keyboard opens. The preview below updates as you drag.',
  appearance_keyboard_height: 'Keyboard height',
  appearance_key_text: 'Letter size',
  appearance_key_gap: 'Space between keys',
  appearance_side_padding: 'Side padding',
  appearance_bottom_padding: 'Bottom padding',
  appearance_haptics: 'Vibrate on keypress',
  appearance_autocorrect: 'Suggestions and autocorrect',
  ai_heading: 'Double-checking (optional)',
  ai_hint: 'Sends a flagged phrase, plus up to a few recent messages, to be reviewed by an AI. It catches things the built-in list misses — and, just as importantly, it recognises when you were joking. Off by default. Your full typing is never sent, and nothing is ever sent from a password field.',
  ai_toggle: 'Turn on double-checking',
  appearance_alarm_heading: 'Alarm size',
  appearance_alarm_hint: 'How large the warning above the keys appears. A warning too small to notice is a warning that does nothing.',
  appearance_alarm_text: 'Warning text size',
  appearance_alarm_lines: 'Message lines shown',
  appearance_preview_heading: 'Preview',
  appearance_preview_sample: 'my address is 123 Main Street',
  appearance_preview_detail: 'Flagged as: Personal information',
  appearance_reset: 'Reset to defaults',
  appearance_value: '%1$s — %2$d%3$s',
  supervision_heading: 'Family supervision',
  supervision_unpaired_hint: 'If a parent has asked you to set this up, they can give you a code. Nothing is shared until you enter one.',
  supervision_label_hint: 'What should this phone be called?',
  supervision_code_hint: 'Pairing code',
  supervision_pair_button: 'Pair with a parent',
  supervision_pairing: 'Pairing…',
  supervision_code_invalid: 'That code isn\'t right, or it has expired. Ask for a new one.',
  supervision_pair_failed: 'Couldn\'t reach the server. Check your connection and try again.',
  supervision_notification_required: 'Supervision needs notifications so this phone always shows that monitoring is on. Allow notifications, then pairing will continue.',
  supervision_restore_notification: 'Turn supervision notification back on',
  supervision_not_configured: 'No server is configured in this build, so supervision can\'t be set up yet.',
  supervision_active_title: 'This device is supervised',
  supervision_active_body: 'A parent can always see:\n\n• The kind of warning you got, and how serious it was\n• Whether you deleted the message or sent it anyway\n• The time it happened\n\nThey can never see:\n\n• Who you were talking to, or which app you were using\n• Anything you type in a password field\n• Messages you receive\n\nHow much else they can see is a setting they choose. The line below says which one is switched on right now, and it will change here if they change it.\n\nWarnings about hurting yourself are included in what they see.\n\nThey can also change how forceful warnings are, whether you are able to dismiss a warning at all, and whether double-checking is switched on.\n\nOnly your parent can end this from their phone. Removing Keyguard also ends it, and they will see that this phone stopped reporting.',
  supervision_last_sync: 'Last sent %1$s',
  supervision_never_synced: 'Nothing sent yet',
  supervision_queued: '%1$d waiting to send',
  supervision_locked_by_parent: 'Set by your parent',
  supervision_channel_name: 'Supervision',
  supervision_channel_description: 'Shows while this device is supervised by a parent.',
  supervision_notice_title: 'Keyguard supervision is on',
  supervision_notice_text: 'A parent can see the warnings you get.',
  supervision_notice_detail: 'A parent can see what kind of warnings you get and whether you sent the message. They cannot see what you typed. Tap for details.',
  supervision_notice_detail_themes: 'A parent can see what kind of warnings you get, whether you sent the message, and a weekly picture of what you talk about. They cannot see what you typed. Tap for details.',
  supervision_notice_detail_full: 'A parent can read what you type on this phone, as well as the warnings you get. Tap for details.',
  supervision_notice_text_full: 'A parent can read what you type.',
  parent_title: 'Parent',
  parent_sign_in_heading: 'Parent account',
  parent_sign_in_hint: 'Sign in to manage your family from this or another phone. New accounts receive a recovery code—save it somewhere private.',
  parent_email_hint: 'Parent email',
  parent_password_hint: 'Password (12 characters or more)',
  parent_login: 'Sign in',
  parent_register: 'Create account',
  parent_recovery_hint: 'Recovery code (only if you lost access)',
  parent_recover: 'Recover account and set this password',
  parent_recovery_code: 'Save this recovery code now. It is shown once:\n%1$s',
  parent_signed_in: 'Signed in as %1$s',
  parent_sign_out: 'Sign out',
  parent_delete_account: 'Delete account',
  parent_delete_account_confirm: 'Delete this parent account, its family, paired devices, and all activity? This cannot be undone.',
  parent_invite_caregiver: 'Invite another parent or caregiver',
  parent_join_code_hint: 'Caregiver invite code',
  parent_join_family: 'Join an existing family',
  parent_auth_invalid: 'Check the email, password, or recovery code and try again.',
  parent_auth_email_used: 'An account already uses that email. Sign in instead.',
  parent_auth_rate_limited: 'Too many attempts. Wait a while and try again.',
  parent_auth_failed: 'Couldn\'t reach the account service.',
  parent_add_child: 'Add a child',
  parent_code_instructions: 'Read this code out on the child\'s phone, under Family supervision. It works once, and expires in 10 minutes.',
  parent_refresh: 'Refresh',
  parent_failed: 'Couldn\'t reach the server.',
  parent_child_quiet: 'No warnings in the last 30 days.',
  parent_event_line: '%1$s · %2$s · %3$s',
  parent_outcome_heeded: 'deleted it',
  parent_outcome_sent: 'sent anyway',
  parent_outcome_abandoned: 'left it unsent',
  parent_remove_child: 'Unpair this device',
  parent_remove_confirm: 'Unpair? Their warning history is deleted and their keyboard goes back to their own settings.',
  parent_policy_min_intensity: 'Least forceful warnings allowed',
  parent_policy_min_intensity_hint: 'A floor, not a setting. They can choose something stronger; they can\'t go below this.',
  parent_policy_lock: 'Don\'t let them change it',
  parent_policy_block: 'Stop typing on serious warnings',
  parent_policy_ai: 'Double-checking by AI',
  parent_policy_ai_hint: 'Double-checking sends flagged phrases to a server. The child must choose whether to send their text; a parent may turn transmission off, but cannot force it on.',
  parent_policy_ai_child: 'Let them choose',
  parent_policy_ai_off: 'Always off',
  parent_policy_save: 'Save',
  parent_policy_saved: 'Saved. Their phone picks it up within about 15 minutes.',
  time_just_now: 'just now',
  time_minutes: '%1$d min ago',
  time_hours: '%1$d h ago',
  time_days: '%1$d d ago',
  overlay_ignore: 'Ignore',
  overlay_remove: 'Remove it',
  overlay_get_help: 'Get help',
  overlay_typing_paused: 'Typing is paused until this is removed.',
  overlay_crisis_detail: '%1$s can help, and it\'s free.',
  accessibility_service_label: 'Keyguard safety warnings',
  accessibility_service_summary: 'Warns before you send something risky',
  accessibility_service_description: 'Keyguard reads the text you are typing so it can warn you before you send personal information, or something that could hurt you or someone else. It never reads password fields. It does not record which app you are using. If this device is supervised, what a parent can see is listed on the Keyguard setup screen.',
  overlay_setup_hint: 'Keyguard now works on top of the keyboard you already use, so typing stays exactly as smooth as it is today. It needs two permissions to do that.',
  overlay_grant_accessibility: 'Allow Keyguard to see what you type',
  overlay_grant_accessibility_hint: 'In the list that opens, find “Keyguard safety warnings” and turn it on.',
  overlay_grant_draw: 'Allow Keyguard to show warnings',
  overlay_grant_draw_hint: 'Without this, Keyguard could watch your typing and have no way to warn you. It will not run until this is on.',
  overlay_status_missing_accessibility: 'Not running: Keyguard cannot see what you type yet.',
  overlay_status_missing_draw: 'Not running: Keyguard cannot show warnings yet.',
  overlay_position_heading: 'Where warnings appear',
  overlay_position_above: 'Above the keyboard',
  overlay_position_top: 'Top of the screen',
  overlay_opacity: 'Warning opacity',
  overlay_enabled_toggle: 'Show warnings while typing',
  role_heading: 'Who is this phone for?',
  role_hint: 'This decides which half of Keyguard you see. You can change it later, unless a parent is supervising this phone.',
  role_child: 'This is the phone being protected',
  role_child_hint: 'Warnings while typing, and pairing with a parent if they ask.',
  role_parent: 'I\'m a parent setting up supervision',
  role_parent_hint: 'Pair a child\'s phone, see their activity, and read daily and weekly reports.',
  role_locked_supervised: 'This phone is supervised. Only the parent who set it up can change this.',
  role_locked_parent: 'Sign out of the parent account first.',
  parent_override_heading: 'What they can do with a warning',
  parent_override_full: 'Ignore any warning',
  parent_override_full_hint: 'They see the warning and decide for themselves. Same as an unsupervised phone.',
  parent_override_limited: 'Ignore small ones only',
  parent_override_limited_hint: 'Serious warnings have to be dealt with; smaller nudges can be waved away.',
  parent_override_none: 'Nothing can be ignored',
  parent_override_none_hint: 'Typing stays paused until the flagged words are removed. There is no Ignore button.',
  parent_scope_heading: 'What you can see',
  parent_scope_concerning: 'Only concerning messages',
  parent_scope_concerning_hint: 'You see that a warning happened, what kind, and what they did about it. You never see any text.',
  parent_scope_themes: 'Topics and mood',
  parent_scope_themes_hint: 'Every message adds a topic and a mood to the weekly picture — school, friends, anxious, excited. You still never see any text.',
  parent_scope_full: 'Everything they type',
  parent_scope_full_hint: 'You can read their messages. This is a big step and they will be told about it in as many words. Most families do not need it.',
  parent_scope_full_confirm: 'Your child will be told that you can read everything they type. Turn this on?',
  parent_reports_toggle: 'Write daily and weekly reports',
  parent_report_daily: 'Today',
  parent_report_weekly: 'This week',
  parent_report_empty: 'Nothing to report yet. Reports appear once their phone has been used for a while.',
  parent_report_basis_concerning: 'Based on warnings only — no messages were collected.',
  parent_report_basis_themes: 'Based on topics and mood — no messages were collected.',
  parent_report_basis_full: 'Based on their messages.',
  parent_report_themes: 'What they talked about',
  parent_report_emotions: 'How they seemed',
  parent_report_concerns: 'Worth a look',
  parent_report_interests: 'What they are into',
  parent_report_counts: '%1$d messages · %2$d flagged',
  parent_report_generated: 'Written %1$s',
  parent_report_failed: 'Could not load the report.',
  supervision_scope_concerning: 'Your parent can see when a warning happens — what kind and what you did about it. They cannot see anything you type.',
  supervision_scope_themes: 'Your parent can see when a warning happens, and a weekly picture of the topics you talk about and how you seem. They cannot see anything you type.',
  supervision_scope_full: 'Your parent has turned on full message review. They can read what you type on this phone.',
  warning_blocked_locked: 'Typing is paused. Remove the highlighted text to carry on.',
  theme_school: 'School',
  theme_friendship: 'Friends',
  theme_family: 'Family',
  theme_romance: 'Relationships',
  theme_gaming: 'Gaming',
  theme_sport: 'Sport',
  theme_music: 'Music and shows',
  theme_online: 'Social media',
  theme_money: 'Money',
  theme_food: 'Food',
  theme_health: 'Health',
  theme_appearance: 'How they look',
  theme_future: 'Plans for the future',
  theme_travel: 'Travel',
  theme_pets: 'Pets',
  theme_creative: 'Making things',
  theme_conflict: 'A falling-out',
  emotion_happy: 'Happy',
  emotion_excited: 'Excited',
  emotion_affectionate: 'Affectionate',
  emotion_sad: 'Sad',
  emotion_anxious: 'Anxious',
  emotion_angry: 'Angry',
  emotion_lonely: 'Lonely',
  emotion_stressed: 'Stressed',
  emotion_tired: 'Tired',
  parent_report_loading: 'Loading…',
  setup_progress_accessibility: 'Step 2 of 3 — let Keyguard see what you type',
  setup_progress_overlay: 'Step 3 of 3 — let Keyguard show warnings',
  onboarding_accessibility_heading: 'Let Keyguard see what you type',
  onboarding_accessibility_body: 'Keyguard works on top of the keyboard you already use, so typing stays exactly as it is. To warn you, it needs to see the text as you write it. It never looks at password fields, and it does not record which app you are in.\n\nIn the list that opens, find “Keyguard safety warnings” and turn it on.',
  onboarding_overlay_heading: 'Let Keyguard show warnings',
  onboarding_overlay_body: 'One more. Keyguard needs permission to draw over other apps so the warning can appear above your keyboard.\n\nWithout it Keyguard would be able to see what you type and have no way to warn you, so it will not run until this is on.',
  nav_protection: 'Protection',
  nav_appearance: 'Look',
  nav_family: 'Family',
  nav_privacy: 'Privacy',
  nav_children: 'Children',
  nav_reports: 'Reports',
  nav_rules: 'Rules',
  nav_account: 'Account',
  protection_on_title: 'You\'re protected',
  protection_on_body: 'Keyguard is watching what you type and will warn you before you send something risky. It never looks at password fields.',
  protection_partial_title: 'Almost there',
  protection_partial_body: 'Keyguard can\'t warn you yet. Finish the step below to turn protection on.',
  protection_off_title: 'Not protected yet',
  protection_off_body: 'Keyguard isn\'t watching anything. Two quick permissions and it will warn you before you send something you might regret.',
  protection_steps_title: 'Setup',
  protection_step_disclosure: 'Read what Keyguard can see',
  protection_step_disclosure_hint: 'Takes a minute. Everything else is switched off until you have.',
  protection_step_disclosure_action: 'Read it',
  protection_step_done: 'Done',
  protection_intensity_hint: 'How forcefully warnings interrupt you. Stronger settings expand the warning and ask before you send.',
  protection_keyboard_title: 'Or use the Keyguard keyboard',
  protection_keyboard_hint: 'An older way to run Keyguard: replace your keyboard instead of running on top of it. You don\'t need this if protection is already on above.',
  appearance_position_hint: 'Above the keyboard is where you\'re already looking. Move it to the top if it covers messages you\'re replying to.',
  appearance_preview_hint: 'The real warning, at your current settings.',
  appearance_opacity_value: '%1$s — %2$d%%',
  parent_add_child_button: 'Get a pairing code',
  parent_children_heading: 'Children',
  parent_caregiver_hint: 'Another parent or carer can join this family and see the same thing you do.',
  parent_invite_caregiver_button: 'Create an invite code',
  parent_danger_heading: 'Account',
  parent_recover_submit: 'Reset password',
  parent_child_last_seen: 'Last seen %1$s',
  parent_child_never_seen: 'Hasn\'t reported yet',
  parent_child_events_heading: 'Recent warnings',
  parent_children_empty: 'No children paired yet. Get a pairing code above and type it into their phone.',
  parent_report_no_children: 'Pair a child\'s phone first, then their reports appear here.',
  protection_step_open_settings: 'Open settings',
  parent_child_more_events: 'and %1$d more',
  parent_report_chip: '%1$s  %2$d',
  onboarding_ready_body_overlay: 'Keyguard is ready. Open any app and start typing — try “my address is 123 Main Street” to see what a warning looks like. Keyguard deliberately ignores its own screens, so it won\'t fire in here.',
} as const;

export type StringKey = keyof typeof S;

/**
 * Fills Android-style positional specifiers.
 *
 * `format(S.parent_report_counts, 42, 3)` -> "42 messages · 3 flagged". Deliberately positional
 * rather than named, because that is the shape the strings already have and rewriting 300 of
 * them to use a different convention would guarantee they drift from the resource file.
 */
export function format(template: string, ...args: (string | number)[]): string {
  return template.replace(/%(\d+)\$[sd]/g, (_match, index) => String(args[Number(index) - 1] ?? ''));
}
